# Generated by Django 2.2.1 on 2019-05-11 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20190511_1457'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='course_category',
            options={'ordering': ['-name'], 'verbose_name': 'Course Category', 'verbose_name_plural': 'Course Categories'},
        ),
        migrations.AlterModelOptions(
            name='course_materials',
            options={'ordering': ['-title'], 'verbose_name': 'Course Material', 'verbose_name_plural': 'Course Materials'},
        ),
        migrations.AddField(
            model_name='course_materials',
            name='latest',
            field=models.BooleanField(default=False),
        ),
    ]
