# Generated by Django 2.2.1 on 2019-05-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_auto_20190511_1505'),
    ]

    operations = [
        migrations.AddField(
            model_name='course_category',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
